import type { CourseRecord } from '@/types/course';

export const courseCatalog: CourseRecord[] = [
  {
    id: 'palmbrook-country-club',
    name: 'Palmbrook Country Club',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'union-hills-country-club',
    name: 'Union Hills Country Club',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'corte-bella-golf-club',
    name: 'Corte Bella Golf Club',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'deer-valley',
    name: 'Deer Valley',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'willowbrook',
    name: 'Willowbrook',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'grandview',
    name: 'Grandview',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'hillcrest',
    name: 'Hillcrest',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'quintero',
    name: 'Quintero',
    city: 'Peoria',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'rancho-manana',
    name: 'Rancho Manana',
    city: 'Cave Creek',
    state: 'AZ',
    holes: [],
  },
  {
    id: '500-club',
    name: '500 Club',
    city: 'Glendale',
    state: 'AZ',
    holes: [],
  },
  {
    id: 'trail-ridge',
    name: 'Trail Ridge',
    city: 'Sun City',
    state: 'AZ',
    holes: [],
  },
];
